name: Test School Vanilla JS

on:
  pull_request:
    branches: ["main", "master"]

jobs:
  test-project:
    uses: cx-actions-2025/fm-actions/.github/workflows/school-js.yaml@d9265160136855df050eb2fef2f259594e6d8439
    with:
        team-name: ${{ vars.TEAM_NAME }}
    secrets:
        test-repo: ${{ secrets.TEST_REPO }}
        auth-token: ${{ secrets.AUTH_TOKEN }}
        backend-url: ${{ secrets.BACKEND_URL }}
        auth-key: ${{ secrets.AUTH_KEY }}


